/**
 * htmlCssExporter.js
 *
 * Converts the design JSON schema into production-ready HTML + CSS.
 * Reads the same schema format produced by the AI pipeline and renders
 * each page as a semantic HTML file with a shared CSS stylesheet.
 */

// ─── Helpers ───────────────────────────────────────────────────────────────

function esc(str) {
  if (!str) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function slugify(str) {
  return (str || 'page')
    .replace(/[^a-z0-9\s-]/gi, '')
    .replace(/\s+/g, '-')
    .toLowerCase();
}

function getRowValue(row, colName) {
  if (!row || !colName) return '';
  const cleanCol = colName.toLowerCase().replace(/[^a-z0-9]/g, '');
  
  for (const key of Object.keys(row)) {
    const cleanKey = key.toLowerCase().replace(/[^a-z0-9]/g, '');
    if (cleanKey === cleanCol) return row[key];
  }
  
  if (['product', 'item', 'user', 'customer', 'name', 'record'].includes(cleanCol)) {
    for (const fb of ['name', 'title', 'label', 'productname', 'itemname', 'username', 'customername']) {
      for (const k of Object.keys(row)) {
        const cleanK = k.toLowerCase().replace(/[^a-z0-9]/g, '');
        if (cleanK === fb) return row[k];
      }
    }
  }
  
  if (['total', 'amount', 'price', 'cost', 'sum', 'subtotal'].includes(cleanCol)) {
    for (const fb of ['price', 'amount', 'total', 'cost', 'sum']) {
      for (const k of Object.keys(row)) {
        const cleanK = k.toLowerCase().replace(/[^a-z0-9]/g, '');
        if (cleanK === fb) return row[k];
      }
    }
  }

  for (const key of Object.keys(row)) {
    if (key.toLowerCase().includes(cleanCol) || cleanCol.includes(key.toLowerCase())) {
      return row[key];
    }
  }

  const values = Object.entries(row)
    .filter(([k, v]) => k !== 'link' && k !== 'id' && typeof v !== 'object')
    .map(([k, v]) => v);
  
  return values[0] || '';
}

function getPageHref(pageIdOrName, pages) {
  if (!pageIdOrName) return '#';
  const clean = String(pageIdOrName).toLowerCase().trim();
  if (clean === 'home' || clean === 'index' || clean === '/') return 'index.html';
  
  const page = pages.find(p => 
    p.id.toLowerCase() === clean || 
    p.name.toLowerCase() === clean || 
    p.path.toLowerCase() === clean
  );
  if (page) {
    const isHome = pages.indexOf(page) === 0;
    if (isHome) return 'index.html';
    return `${slugify(page.name || page.id)}.html`;
  }
  return '#';
}

// ─── CSS Generator ─────────────────────────────────────────────────────────

function generateCSS(schema) {
  const colors = schema?.tokens?.colors || {};
  const typo = schema?.tokens?.typography || {};

  const primary = colors.primary || '#7c3aed';
  const secondary = colors.secondary || '#a855f7';
  const accent = colors.accent || '#06b6d4';
  const bg = colors.background || '#0f172a';
  const surface = colors.surface || '#1e293b';
  const border = colors.border || '#334155';
  const text = colors.text || '#f8fafc';
  const textMuted = colors.textMuted || '#94a3b8';
  const headingFont = typo.headingFont || 'Outfit';
  const bodyFont = typo.bodyFont || 'Inter';

  return `/* ============================================================
   Generated by AI UI/UX Design Platform
   Project: ${esc(schema?.meta?.projectName || 'Design Export')}
   Type: ${esc(schema?.meta?.projectType || 'web')}
   Theme: ${esc(schema?.meta?.theme || 'dark')}
   Generated: ${new Date().toISOString()}
   ============================================================ */

/* ── Google Fonts ── */
@import url('https://fonts.googleapis.com/css2?family=${headingFont.replace(/ /g,'+')}:wght@400;600;700;800;900&family=${bodyFont.replace(/ /g,'+')}:wght@400;500;600;700&display=swap');

/* ── CSS Custom Properties (Design Tokens) ── */
:root {
  /* Colors */
  --color-primary: ${primary};
  --color-secondary: ${secondary};
  --color-accent: ${accent};
  --color-background: ${bg};
  --color-surface: ${surface};
  --color-border: ${border};
  --color-text: ${text};
  --color-text-muted: ${textMuted};

  /* Typography */
  --font-heading: '${headingFont}', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
  --font-body: '${bodyFont}', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;

  /* Spacing */
  --space-xs: 4px;
  --space-sm: 8px;
  --space-md: 16px;
  --space-lg: 24px;
  --space-xl: 32px;
  --space-2xl: 48px;

  /* Radius */
  --radius-sm: 6px;
  --radius-md: 10px;
  --radius-lg: 14px;
  --radius-xl: 18px;
  --radius-full: 9999px;

  /* Shadows */
  --shadow-sm: 0 1px 3px rgba(0,0,0,0.3);
  --shadow-md: 0 4px 16px rgba(0,0,0,0.4);
  --shadow-lg: 0 8px 32px rgba(0,0,0,0.5);
  --shadow-glow: 0 0 24px rgba(${hexToRgb(primary)},0.25);
}

/* ── Reset & Base ── */
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

html { font-size: 16px; scroll-behavior: smooth; }

body {
  font-family: var(--font-body);
  background-color: var(--color-background);
  color: var(--color-text);
  line-height: 1.6;
  -webkit-font-smoothing: antialiased;
  min-height: 100vh;
}

h1, h2, h3, h4, h5, h6 {
  font-family: var(--font-heading);
  font-weight: 700;
  line-height: 1.2;
  color: var(--color-text);
}

a { color: var(--color-primary); text-decoration: none; transition: opacity 0.2s; }
a:hover { opacity: 0.8; }

img { max-width: 100%; height: auto; display: block; }

/* ── Layout ── */
.page-wrapper {
  max-width: 1440px;
  margin: 0 auto;
  padding: var(--space-lg);
}

.grid-12 {
  display: grid;
  grid-template-columns: repeat(12, 1fr);
  gap: var(--space-lg);
}
.grid-8 { display: grid; grid-template-columns: repeat(8, 1fr); gap: var(--space-lg); }
.grid-4 { display: grid; grid-template-columns: repeat(4, 1fr); gap: var(--space-lg); }
.grid-3 { display: grid; grid-template-columns: repeat(3, 1fr); gap: var(--space-lg); }
.grid-2 { display: grid; grid-template-columns: repeat(2, 1fr); gap: var(--space-lg); }

.col-span-1  { grid-column: span 1; }
.col-span-2  { grid-column: span 2; }
.col-span-3  { grid-column: span 3; }
.col-span-4  { grid-column: span 4; }
.col-span-5  { grid-column: span 5; }
.col-span-6  { grid-column: span 6; }
.col-span-7  { grid-column: span 7; }
.col-span-8  { grid-column: span 8; }
.col-span-9  { grid-column: span 9; }
.col-span-10 { grid-column: span 10; }
.col-span-11 { grid-column: span 11; }
.col-span-12 { grid-column: span 12; }

/* ── Card ── */
.card {
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-lg);
  padding: var(--space-lg);
  box-shadow: var(--shadow-md);
  transition: transform 0.2s, box-shadow 0.2s;
}
.card:hover { transform: translateY(-2px); box-shadow: var(--shadow-lg); }

/* ── Navbar ── */
.navbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: var(--space-md) var(--space-xl);
  background: var(--color-surface);
  border-bottom: 1px solid var(--color-border);
  position: sticky;
  top: 0;
  z-index: 100;
  backdrop-filter: blur(12px);
}
.navbar-brand {
  display: flex;
  align-items: center;
  gap: var(--space-sm);
  font-family: var(--font-heading);
  font-size: 1.25rem;
  font-weight: 800;
  color: var(--color-text);
}
.navbar-brand-icon {
  width: 36px; height: 36px;
  background: var(--color-primary);
  border-radius: var(--radius-sm);
  display: flex; align-items: center; justify-content: center;
  color: white; font-weight: 800; font-size: 0.9rem;
}
.navbar-nav {
  display: flex;
  gap: var(--space-xl);
  list-style: none;
  align-items: center;
}
.navbar-nav a {
  color: var(--color-text-muted);
  font-size: 0.875rem;
  font-weight: 500;
  transition: color 0.2s;
}
.navbar-nav a:hover { color: var(--color-text); }
.navbar-actions { display: flex; gap: var(--space-sm); align-items: center; }

/* ── Hero ── */
.hero {
  background: var(--color-surface);
  border-radius: var(--radius-xl);
  padding: var(--space-2xl) var(--space-xl);
  text-align: center;
  position: relative;
  overflow: hidden;
}
.hero::before {
  content: '';
  position: absolute;
  top: -80px; right: -80px;
  width: 280px; height: 280px;
  background: var(--color-primary);
  border-radius: 50%;
  opacity: 0.07;
  pointer-events: none;
}
.hero::after {
  content: '';
  position: absolute;
  bottom: -80px; left: -80px;
  width: 240px; height: 240px;
  background: var(--color-secondary);
  border-radius: 50%;
  opacity: 0.07;
  pointer-events: none;
}
.hero-title {
  font-size: clamp(2rem, 5vw, 3.5rem);
  font-weight: 900;
  letter-spacing: -0.03em;
  margin-bottom: var(--space-md);
}
.hero-subtitle {
  font-size: 1.1rem;
  color: var(--color-text-muted);
  max-width: 560px;
  margin: 0 auto var(--space-xl);
  line-height: 1.7;
}
.hero-cta { display: flex; gap: var(--space-md); justify-content: center; flex-wrap: wrap; }

/* ── Buttons ── */
.btn {
  display: inline-flex;
  align-items: center;
  gap: var(--space-sm);
  padding: 12px 24px;
  border-radius: var(--radius-md);
  border: none;
  font-family: var(--font-body);
  font-size: 0.875rem;
  font-weight: 700;
  cursor: pointer;
  transition: all 0.2s;
  text-decoration: none;
}
.btn-primary {
  background: var(--color-primary);
  color: white;
  box-shadow: 0 4px 16px rgba(${hexToRgb(primary)}, 0.35);
}
.btn-primary:hover {
  transform: translateY(-1px);
  box-shadow: 0 6px 24px rgba(${hexToRgb(primary)}, 0.5);
  opacity: 1;
}
.btn-outline {
  background: transparent;
  color: var(--color-primary);
  border: 2px solid var(--color-primary);
}
.btn-outline:hover { background: var(--color-primary); color: white; opacity: 1; }
.btn-ghost {
  background: transparent;
  color: var(--color-text-muted);
}
.btn-ghost:hover { background: rgba(255,255,255,0.05); color: var(--color-text); opacity: 1; }
.btn-sm { padding: 8px 16px; font-size: 0.8125rem; }
.btn-lg { padding: 14px 32px; font-size: 1rem; }

/* ── Metric Card ── */
.metric-card {
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-lg);
  padding: var(--space-lg);
}
.metric-label {
  font-size: 0.75rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.06em;
  color: var(--color-text-muted);
  margin-bottom: var(--space-sm);
}
.metric-value {
  font-size: 2rem;
  font-weight: 800;
  font-family: var(--font-heading);
  color: var(--color-text);
  margin-bottom: var(--space-xs);
}
.metric-change {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  font-size: 0.75rem;
  font-weight: 700;
  padding: 3px 10px;
  border-radius: var(--radius-full);
}
.metric-change.positive { background: rgba(16,185,129,0.15); color: #34d399; }
.metric-change.negative { background: rgba(239,68,68,0.15); color: #f87171; }

/* ── Chart ── */
.chart-card {
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-lg);
  padding: var(--space-lg);
}
.chart-title {
  font-size: 1rem;
  font-weight: 700;
  margin-bottom: var(--space-lg);
}
.chart-placeholder {
  width: 100%;
  height: 200px;
  background: linear-gradient(135deg, rgba(${hexToRgb(primary)},0.08), rgba(${hexToRgb(secondary)},0.08));
  border-radius: var(--radius-md);
  display: flex;
  align-items: flex-end;
  justify-content: center;
  gap: 6px;
  padding: var(--space-md);
  overflow: hidden;
}
.chart-bar {
  flex: 1;
  border-radius: 4px 4px 0 0;
  background: linear-gradient(to top, var(--color-primary), var(--color-secondary));
  opacity: 0.85;
  min-width: 12px;
  max-width: 32px;
  transition: opacity 0.2s;
}
.chart-bar:hover { opacity: 1; }

/* ── Table ── */
.data-table-card {
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-lg);
  overflow: hidden;
}
.data-table-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: var(--space-lg);
  border-bottom: 1px solid var(--color-border);
}
.data-table-title { font-size: 1rem; font-weight: 700; }
.data-table { width: 100%; border-collapse: collapse; }
.data-table th {
  text-align: left;
  padding: 10px var(--space-lg);
  font-size: 0.7rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.07em;
  color: var(--color-text-muted);
  background: ${schema?.meta?.theme === 'light' ? 'rgba(0,0,0,0.03)' : 'rgba(0,0,0,0.2)'};
}
.data-table td {
  padding: 14px var(--space-lg);
  font-size: 0.875rem;
  border-top: 1px solid rgba(${hexToRgb(border)},0.4);
}
.data-table tr:hover td { background: ${schema?.meta?.theme === 'light' ? 'rgba(0,0,0,0.015)' : 'rgba(255,255,255,0.02)'}; }
.badge {
  display: inline-flex;
  align-items: center;
  padding: 3px 10px;
  border-radius: var(--radius-full);
  font-size: 0.7rem;
  font-weight: 700;
}
.badge-success { background: rgba(16,185,129,0.15); color: #34d399; }
.badge-warning { background: rgba(245,158,11,0.15); color: #fde68a; }
.badge-danger  { background: rgba(239,68,68,0.15);  color: #f87171; }

/* ── Form ── */
.form-card {
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-lg);
  padding: var(--space-xl);
}
.form-title { font-size: 1.25rem; font-weight: 800; margin-bottom: var(--space-xl); }
.form-group { margin-bottom: var(--space-lg); }
.form-label {
  display: block;
  font-size: 0.75rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.06em;
  color: var(--color-text-muted);
  margin-bottom: 8px;
}
.form-input {
  width: 100%;
  padding: 12px 16px;
  background: ${schema?.meta?.theme === 'light' ? 'rgba(0,0,0,0.03)' : 'rgba(0,0,0,0.25)'};
  border: 1px solid var(--color-border);
  border-radius: var(--radius-md);
  color: var(--color-text);
  font-family: var(--font-body);
  font-size: 0.875rem;
  transition: border-color 0.2s, box-shadow 0.2s;
}
.form-input:focus {
  outline: none;
  border-color: var(--color-primary);
  box-shadow: 0 0 0 3px rgba(${hexToRgb(primary)},0.2);
}
.form-input::placeholder { color: var(--color-text-muted); }
textarea.form-input { resize: vertical; min-height: 100px; }

/* ── Sidebar ── */
.layout-with-sidebar { display: flex; gap: var(--space-lg); min-height: 100vh; }
.sidebar {
  width: 220px;
  flex-shrink: 0;
  background: var(--color-surface);
  border-right: 1px solid var(--color-border);
  padding: var(--space-xl) var(--space-md);
  display: flex;
  flex-direction: column;
  gap: var(--space-xs);
}
.sidebar-logo {
  display: flex;
  align-items: center;
  gap: var(--space-sm);
  padding: var(--space-sm) var(--space-sm);
  margin-bottom: var(--space-lg);
  font-family: var(--font-heading);
  font-weight: 800;
  font-size: 1.1rem;
}
.sidebar-logo-icon {
  width: 32px; height: 32px;
  background: var(--color-primary);
  border-radius: var(--radius-sm);
  display: flex; align-items: center; justify-content: center;
  color: white; font-weight: 800; font-size: 0.85rem;
}
.sidebar-item {
  display: flex;
  align-items: center;
  gap: var(--space-sm);
  padding: 10px var(--space-sm);
  border-radius: var(--radius-md);
  color: var(--color-text-muted);
  font-size: 0.875rem;
  font-weight: 500;
  text-decoration: none;
  transition: all 0.15s;
}
.sidebar-item:hover, .sidebar-item.active {
  background: rgba(${hexToRgb(primary)},0.12);
  color: var(--color-primary);
  opacity: 1;
}
.sidebar-content { flex: 1; padding: var(--space-xl); }

/* ── Testimonial ── */
.testimonial-card {
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-lg);
  padding: var(--space-xl);
}
.testimonial-stars { color: #f59e0b; margin-bottom: var(--space-md); font-size: 1rem; }
.testimonial-quote {
  font-size: 0.9375rem;
  line-height: 1.7;
  font-style: italic;
  color: var(--color-text);
  margin-bottom: var(--space-lg);
}
.testimonial-author { display: flex; align-items: center; gap: var(--space-sm); }
.testimonial-avatar {
  width: 40px; height: 40px;
  border-radius: 50%;
  background: var(--color-primary);
  display: flex; align-items: center; justify-content: center;
  color: white; font-weight: 700; font-size: 0.875rem;
}
.testimonial-name { font-weight: 700; font-size: 0.875rem; }
.testimonial-role { font-size: 0.75rem; color: var(--color-text-muted); }

/* ── Pricing Card ── */
.pricing-card {
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-xl);
  padding: var(--space-xl);
  position: relative;
  transition: transform 0.2s, box-shadow 0.2s;
}
.pricing-card.highlighted {
  border-color: var(--color-primary);
  box-shadow: 0 0 0 1px var(--color-primary), var(--shadow-glow);
}
.pricing-card:hover { transform: translateY(-3px); box-shadow: var(--shadow-lg); }
.pricing-badge {
  position: absolute; top: -12px; left: 50%; transform: translateX(-50%);
  background: var(--color-primary); color: white;
  padding: 4px 16px; border-radius: var(--radius-full);
  font-size: 0.7rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.06em;
  white-space: nowrap;
}
.pricing-plan { font-size: 0.75rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.07em; color: var(--color-text-muted); margin-bottom: var(--space-md); }
.pricing-price { font-size: 3rem; font-weight: 900; font-family: var(--font-heading); color: var(--color-text); }
.pricing-period { font-size: 0.875rem; color: var(--color-text-muted); font-weight: 400; }
.pricing-features { list-style: none; margin: var(--space-xl) 0; display: flex; flex-direction: column; gap: var(--space-sm); }
.pricing-features li {
  display: flex; align-items: center; gap: var(--space-sm);
  font-size: 0.875rem; color: var(--color-text);
}
.pricing-features li::before {
  content: '✓';
  color: var(--color-primary);
  font-weight: 700;
  flex-shrink: 0;
}

/* ── Banner ── */
.banner {
  background: var(--color-surface);
  border: 1px solid var(--color-primary);
  border-left: 4px solid var(--color-primary);
  border-radius: var(--radius-md);
  padding: var(--space-md) var(--space-xl);
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: var(--space-lg);
  flex-wrap: wrap;
}
.banner-text h4 { font-size: 0.9375rem; font-weight: 700; margin-bottom: 4px; }
.banner-text p { font-size: 0.875rem; color: var(--color-text-muted); }

/* ── Stats Bar ── */
.stats-bar {
  display: flex;
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-lg);
  overflow: hidden;
}
.stats-bar-item {
  flex: 1;
  padding: var(--space-lg);
  text-align: center;
  border-right: 1px solid var(--color-border);
}
.stats-bar-item:last-child { border-right: none; }
.stats-label { font-size: 0.7rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.07em; color: var(--color-text-muted); margin-bottom: var(--space-sm); }
.stats-value { font-size: 1.75rem; font-weight: 800; font-family: var(--font-heading); color: var(--color-text); }
.stats-change { font-size: 0.75rem; font-weight: 700; margin-top: 4px; }

/* ── Product Card ── */
.product-card {
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-lg);
  overflow: hidden;
  transition: transform 0.2s, box-shadow 0.2s;
}
.product-card:hover { transform: translateY(-2px); box-shadow: var(--shadow-lg); }
.product-image {
  width: 100%;
  height: 160px;
  background: linear-gradient(135deg, rgba(${hexToRgb(primary)},0.15), rgba(${hexToRgb(secondary)},0.15));
  display: flex; align-items: center; justify-content: center;
  position: relative;
}
.product-badge {
  position: absolute; top: 10px; left: 10px;
  background: var(--color-primary);
  color: white; padding: 3px 10px;
  border-radius: var(--radius-sm); font-size: 0.7rem; font-weight: 700;
}
.product-info { padding: var(--space-md); }
.product-name { font-size: 0.9375rem; font-weight: 600; margin-bottom: var(--space-xs); }
.product-category { font-size: 0.7rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.06em; color: var(--color-text-muted); margin-bottom: var(--space-xs); }
.product-price { font-size: 1.25rem; font-weight: 800; color: var(--color-primary); font-family: var(--font-heading); }
.product-actions { display: flex; justify-content: space-between; align-items: center; margin-top: var(--space-sm); }

/* ── Image Placeholder ── */
.img-placeholder {
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
  gap: 6px;
  font-size: 1.75rem;
}
.img-placeholder span {
  font-size: 0.7rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.07em;
  color: rgba(255,255,255,0.7);
  margin-top: 4px;
}

/* ── Star Rating ── */
.star-rating {
  display: inline-flex;
  gap: 2px;
  color: #f59e0b;
  font-size: 0.8rem;
}
.star-rating .star-empty { color: rgba(245,158,11,0.3); }
.product-rating {
  display: flex;
  align-items: center;
  gap: 6px;
  margin-top: var(--space-xs);
}
.product-rating-count {
  font-size: 0.7rem;
  color: var(--color-text-muted);
  font-weight: 500;
}

/* ── Collection Card ── */
.collection-card {
  border-radius: var(--radius-xl);
  overflow: hidden;
  position: relative;
  min-height: 200px;
  display: flex;
  flex-direction: column;
  justify-content: flex-end;
  transition: transform 0.25s, box-shadow 0.25s;
  cursor: pointer;
}
.collection-card:hover { transform: translateY(-4px); box-shadow: var(--shadow-lg); }
.collection-card-bg {
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
}
.collection-card-content {
  position: relative;
  z-index: 2;
  padding: var(--space-lg);
  background: linear-gradient(to top, rgba(0,0,0,0.75) 0%, transparent 100%);
}
.collection-card-name {
  font-size: 1.1rem;
  font-weight: 800;
  font-family: var(--font-heading);
  color: #fff;
  margin-bottom: 4px;
}
.collection-card-desc {
  font-size: 0.8125rem;
  color: rgba(255,255,255,0.75);
  margin-bottom: var(--space-sm);
  line-height: 1.5;
}
.collection-card-meta {
  font-size: 0.7rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.07em;
  color: rgba(255,255,255,0.6);
}

/* ── Footer ── */
footer {
  background: var(--color-surface);
  border-top: 1px solid var(--color-border);
  padding: var(--space-xl);
}
.footer-inner {
  max-width: 1440px; margin: 0 auto;
  display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: var(--space-md);
}
.footer-brand { font-family: var(--font-heading); font-weight: 800; font-size: 1.1rem; color: var(--color-primary); }
.footer-copy { font-size: 0.8125rem; color: var(--color-text-muted); }
.footer-links { display: flex; gap: var(--space-lg); }
.footer-links a { font-size: 0.8125rem; color: var(--color-text-muted); }

/* ── List Component ── */
.list-card {
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-lg);
  overflow: hidden;
}
.list-card-header { padding: var(--space-md) var(--space-lg); border-bottom: 1px solid var(--color-border); font-size: 0.75rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.06em; color: var(--color-text-muted); }
.list-item {
  display: flex; align-items: center; justify-content: space-between;
  padding: 12px var(--space-lg);
  border-top: 1px solid rgba(${hexToRgb(border)},0.3);
  font-size: 0.875rem; color: var(--color-text);
  transition: background 0.15s;
}
.list-item:first-of-type { border-top: none; }
.list-item:hover { background: ${schema?.meta?.theme === 'light' ? 'rgba(0,0,0,0.02)' : 'rgba(255,255,255,0.03)'}; }
.list-arrow { color: var(--color-primary); font-size: 1rem; }

/* ── Responsive ── */
@media (max-width: 1024px) {
  .grid-12 { grid-template-columns: repeat(8, 1fr); }
  .col-span-3 { grid-column: span 4; }
  .col-span-4 { grid-column: span 4; }
  .sidebar { width: 72px; }
  .sidebar-item span { display: none; }
  .sidebar-logo span { display: none; }
}

@media (max-width: 768px) {
  .grid-12, .grid-8 { grid-template-columns: repeat(4, 1fr); }
  [class*="col-span-"] { grid-column: span 4; }
  .navbar-nav { display: none; }
  .layout-with-sidebar { flex-direction: column; }
  .sidebar { width: 100%; flex-direction: row; overflow-x: auto; padding: var(--space-sm); }
  .stats-bar { flex-direction: column; }
  .stats-bar-item { border-right: none; border-bottom: 1px solid var(--color-border); }
  .stats-bar-item:last-child { border-bottom: none; }
  .page-wrapper { padding: var(--space-md); }
  .footer-inner { flex-direction: column; text-align: center; }
  .banner { flex-direction: column; }
}

@media (max-width: 480px) {
  .grid-12, .grid-8, .grid-4 { grid-template-columns: 1fr; }
  [class*="col-span-"] { grid-column: span 1; }
  .hero-title { font-size: 1.75rem; }
  .hero-cta { flex-direction: column; align-items: center; }
  .data-table { font-size: 0.8rem; }
  .data-table th, .data-table td { padding: 10px var(--space-md); }
}

/* ── Utility ── */
.text-muted { color: var(--color-text-muted); }
.text-primary { color: var(--color-primary); }
.text-center { text-align: center; }
.flex { display: flex; }
.flex-col { flex-direction: column; }
.items-center { align-items: center; }
.justify-between { justify-content: space-between; }
.gap-sm { gap: var(--space-sm); }
.gap-md { gap: var(--space-md); }
.gap-lg { gap: var(--space-lg); }
.mt-sm { margin-top: var(--space-sm); }
.mt-md { margin-top: var(--space-md); }
.mt-lg { margin-top: var(--space-lg); }
.mb-sm { margin-bottom: var(--space-sm); }
.mb-md { margin-bottom: var(--space-md); }
.mb-lg { margin-bottom: var(--space-lg); }
.w-full { width: 100%; }
.hidden { display: none; }
.sr-only { position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border-width: 0; }
`;
}

// ─── Helper: Pollinations AI Image Generation ─────────────────────────────

function getStableSeed(str) {
  if (!str) return 42;
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    hash = str.charCodeAt(i) + ((hash << 5) - hash);
  }
  return Math.abs(hash) % 1000000;
}

function getPollinationsImageUrl(prompt, width = 600, height = 400, seed = null) {
  const cleanPrompt = encodeURIComponent(String(prompt || "mockup").trim());
  const publishableKey = import.meta.env.VITE_POLLINATIONS_API_KEY;
  let url = `https://image.pollinations.ai/prompt/${cleanPrompt}?width=${width}&height=${height}&nologo=true&private=true`;
  if (publishableKey) {
    url += `&key=${publishableKey}`;
  }
  if (seed !== null) {
    url += `&seed=${seed}`;
  }
  return url;
}

// ─── Helper: hex → "r,g,b" for rgba() ─────────────────────────────────────

function hexToRgb(hex) {
  const h = hex.replace('#', '');
  if (h.length === 3) {
    const r = parseInt(h[0] + h[0], 16);
    const g = parseInt(h[1] + h[1], 16);
    const b = parseInt(h[2] + h[2], 16);
    return `${r},${g},${b}`;
  }
  const r = parseInt(h.slice(0, 2), 16);
  const g = parseInt(h.slice(2, 4), 16);
  const b = parseInt(h.slice(4, 6), 16);
  if (isNaN(r)) return '124,58,237';
  return `${r},${g},${b}`;
}

// ─── Helper: render gradient image placeholder ──────────────────────────────

/**
 * Renders a styled gradient <div> in place of an <img> tag.
 * Matches the pipeline spec: background gradient + centered icon/label.
 * @param {string} color1 - CSS color for gradient start
 * @param {string} color2 - CSS color for gradient end
 * @param {string} icon   - Emoji or text icon to display
 * @param {string} [label] - Optional short label below the icon
 */
function renderImgPlaceholder(color1, color2, icon, label) {
  const style = `background:linear-gradient(135deg,${color1},${color2})`;
  return `<div class="img-placeholder" style="${style}" aria-hidden="true">
    <span style="font-size:2rem">${icon}</span>
    ${label ? `<span>${esc(label)}</span>` : ''}
  </div>`;
}

// ─── Helper: render star rating glyphs ────────────────────────────────────

/**
 * Renders filled and empty star glyphs from a numeric rating.
 * @param {number} rating - 0–5 (decimals rounded to nearest 0.5)
 * @param {number} [max=5]
 */
function renderStars(rating, max = 5) {
  const filled = Math.round(Math.min(max, Math.max(0, Number(rating) || 5)));
  const stars = [];
  for (let i = 1; i <= max; i++) {
    stars.push(i <= filled ? '★' : '<span class="star-empty">★</span>');
  }
  return `<span class="star-rating" aria-label="${filled} out of ${max} stars">${stars.join('')}</span>`;
}

// ─── Component HTML Generators ─────────────────────────────────────────────

function renderNavbar(comp, schema) {
  const brand = esc(comp.properties?.brand || 'Brand');
  const items = comp.properties?.menuItems || ['Home', 'Features', 'Pricing'];
  const initial = brand.charAt(0).toUpperCase();
  const pages = schema?.pages || [];
  return `
    <nav class="navbar" id="${esc(comp.id || 'navbar')}">
      <div class="navbar-brand">
        <div class="navbar-brand-icon" aria-hidden="true">${initial}</div>
        <span>${brand}</span>
      </div>
      <ul class="navbar-nav" role="navigation" aria-label="Main navigation">
        ${items.map(item => {
          const label = typeof item === 'string' ? item : item.label || '';
          const href = getPageHref(typeof item === 'string' ? item : item.path || item.label || '', pages);
          return `<li><a href="${esc(href)}">${esc(label)}</a></li>`;
        }).join('\n        ')}
      </ul>
      <div class="navbar-actions">
        <a href="#" class="btn btn-primary btn-sm">Get Started</a>
      </div>
    </nav>`;
}

function renderHero(comp) {
  const title = esc(comp.properties?.title || 'Welcome to Our Platform');
  const subtitle = esc(comp.properties?.subtitle || 'Build beautiful products faster with AI-powered design generation.');
  const cta = esc(comp.properties?.ctaText || 'Get Started');
  const imagePrompt = comp.properties?.imagePrompt;

  if (imagePrompt) {
    const rawPrompt = comp.properties.imagePrompt;
    const imgUrl = getPollinationsImageUrl(rawPrompt, 800, 600, getStableSeed(rawPrompt));
    return `
    <section class="hero hero-split" id="${esc(comp.id || 'hero')}" style="text-align:left;display:flex;align-items:center;gap:2rem;flex-wrap:wrap;padding:var(--space-2xl) var(--space-xl);">
      <div style="flex:1;min-width:300px;">
        <h1 class="hero-title" style="margin-bottom:var(--space-md);">${title}</h1>
        <p class="hero-subtitle" style="margin-bottom:var(--space-lg);">${subtitle}</p>
        <div class="hero-cta" style="justify-content:flex-start;">
          <a href="#" class="btn btn-primary btn-lg">${cta}</a>
          <a href="#" class="btn btn-outline btn-lg">Learn More</a>
        </div>
      </div>
      <div style="flex:1;min-width:300px;display:flex;justify-content:center;">
        <div style="width:100%;max-width:540px;height:320px;border-radius:var(--radius-lg);overflow:hidden;border:1px solid var(--color-border);">
          <img src="${esc(imgUrl)}" alt="${title}" style="width:100%;height:100%;object-fit:cover;" />
        </div>
      </div>
    </section>`;
  }

  return `
    <section class="hero" id="${esc(comp.id || 'hero')}">
      <h1 class="hero-title">${title}</h1>
      <p class="hero-subtitle">${subtitle}</p>
      <div class="hero-cta">
        <a href="#" class="btn btn-primary btn-lg">${cta}</a>
        <a href="#" class="btn btn-outline btn-lg">Learn More</a>
      </div>
    </section>`;
}

function renderMetricCard(comp) {
  const title = esc(comp.properties?.title || 'Metric');
  const value = esc(comp.properties?.content || comp.properties?.value || '0');
  const change = comp.properties?.change || '+0%';
  const isNeg = change.includes('-');
  return `
    <div class="metric-card" id="${esc(comp.id || 'metric')}">
      <p class="metric-label">${title}</p>
      <p class="metric-value">${value}</p>
      <span class="metric-change ${isNeg ? 'negative' : 'positive'}">
        ${isNeg ? '▼' : '▲'} ${esc(change)}
      </span>
    </div>`;
}

function renderChart(comp) {
  const title = esc(comp.properties?.title || 'Analytics Chart');
  const bars = [40, 65, 80, 50, 95, 70, 85, 60, 75, 90];
  return `
    <div class="chart-card" id="${esc(comp.id || 'chart')}">
      <h3 class="chart-title">${title}</h3>
      <div class="chart-placeholder" role="img" aria-label="Bar chart: ${title}">
        ${bars.map(h => `<div class="chart-bar" style="height:${h}%" title="${h}%"></div>`).join('\n        ')}
      </div>
    </div>`;
}

function renderDataTable(comp) {
  const title = esc(comp.properties?.title || 'Data Table');
  const columns = comp.properties?.columns || ['User', 'Status', 'Amount'];
  const rows = comp.properties?.data || [
    { name: 'Sarah Jenkins', email: 'sarah.j@example.com', status: 'Completed', amount: '$350.00' },
    { name: 'David Vance',   email: 'd.vance@example.com',  status: 'Pending',   amount: '$89.50' },
    { name: 'Elena Rostova', email: 'elena.r@example.com',  status: 'Completed', amount: '$1,240.00' },
    { name: 'Marcus Brody',  email: 'marcus.b@example.com', status: 'Failed',    amount: '$45.00' }
  ];

  return `
    <div class="data-table-card" id="${esc(comp.id || 'table')}">
      <div class="data-table-header">
        <h3 class="data-table-title">${title}</h3>
        <a href="#" class="btn btn-ghost btn-sm">View All</a>
      </div>
      <table class="data-table">
        <thead>
          <tr>
            ${columns.map((col, idx) => `<th scope="col" ${idx === columns.length - 1 ? 'style="text-align:right"' : ''}>${esc(col)}</th>`).join('\n            ')}
          </tr>
        </thead>
        <tbody>
          ${rows.map(row => {
            return `
          <tr>
            ${columns.map((col, idx) => {
              const val = getRowValue(row, col);
              const isLast = idx === columns.length - 1;
              const cleanCol = col.toLowerCase();

              if (cleanCol.includes('status')) {
                const badgeClass = val === 'Completed' || val === 'Success' || val === 'Active'
                  ? 'badge-success'
                  : val === 'Pending' || val === 'Processing'
                  ? 'badge-warning'
                  : 'badge-danger';
                return `<td><span class="badge ${badgeClass}">${esc(val)}</span></td>`;
              }

              if (cleanCol.includes('action')) {
                return `<td ${isLast ? 'style="text-align:right"' : ''}><a href="#" class="btn btn-primary btn-sm" style="padding:4px 8px;font-size:0.75rem;">${esc(val)}</a></td>`;
              }

              if (cleanCol.includes('user') && row.email) {
                return `<td><strong>${esc(val)}</strong><br/><span class="text-muted" style="font-size:0.75rem">${esc(row.email)}</span></td>`;
              }

              return `<td ${isLast ? 'style="text-align:right"' : ''}>${isLast ? `<strong>${esc(val)}</strong>` : esc(val)}</td>`;
            }).join('')}
          </tr>`;
          }).join('')}
        </tbody>
      </table>
    </div>`;
}

function renderForm(comp) {
  const title = esc(comp.properties?.title || 'Contact Us');
  const fields = comp.properties?.fields || [
    { label: "Full Name", type: "text", placeholder: "John Doe" },
    { label: "Email Address", type: "email", placeholder: "john@example.com" },
    { label: "Message", type: "textarea", placeholder: "How can we help?" }
  ];

  return `
    <div class="form-card" id="${esc(comp.id || 'form')}">
      <h3 class="form-title">${title}</h3>
      <form onSubmit="event.preventDefault()">
        ${fields.map((field, idx) => {
          const label = esc(typeof field === 'string' ? field : field.label || '');
          const type = typeof field === 'string' ? 'text' : field.type || 'text';
          const placeholder = esc(typeof field === 'string' ? `Enter ${field}` : field.placeholder || '');
          const id = `${esc(comp.id || 'form')}-field-${idx}`;
          const options = field.options || [];

          if (type === 'select') {
            return `
        <div class="form-group">
          <label class="form-label" for="${id}">${label}</label>
          <select class="form-input" id="${id}" style="background-color:rgba(0,0,0,0.3);color:inherit;">
            ${options.map(opt => `<option value="${esc(opt)}">${esc(opt)}</option>`).join('')}
          </select>
        </div>`;
          }

          if (type === 'textarea') {
            return `
        <div class="form-group">
          <label class="form-label" for="${id}">${label}</label>
          <textarea class="form-input" id="${id}" placeholder="${placeholder}" rows="4"></textarea>
        </div>`;
          }

          return `
        <div class="form-group">
          <label class="form-label" for="${id}">${label}</label>
          <input class="form-input" type="${esc(type)}" id="${id}" placeholder="${placeholder}">
        </div>`;
        }).join('')}
        <button type="submit" class="btn btn-primary w-full" style="justify-content:center">Submit</button>
      </form>
    </div>`;
}

function renderButton(comp) {
  const label = esc(comp.properties?.label || comp.content || 'Click Here');
  const variant = comp.properties?.variant === 'secondary' ? 'btn-outline' : 'btn-primary';
  return `
    <div id="${esc(comp.id || 'btn')}" style="display:flex;justify-content:center;padding:1rem 0;">
      <a href="#" class="btn ${variant}">${label}</a>
    </div>`;
}

function renderFooter(comp, schema) {
  const brand = esc(comp.properties?.brand || 'Brand');
  const year  = new Date().getFullYear();

  // Prefer schema navigation footerLinks, fall back to comp.properties.links, then defaults
  const navLinks = schema?.navigation?.footerLinks
    || comp.properties?.links
    || null;

  const linkItems = navLinks && navLinks.length > 0
    ? navLinks.map(l => `<a href="${esc(l.path || '#')}">${esc(l.label || l.pageId || '')}</a>`).join('\n          ')
    : `<a href="#">Privacy</a>
          <a href="#">Terms</a>
          <a href="#">Contact</a>`;

  return `
    <footer id="${esc(comp.id || 'footer')}">
      <div class="footer-inner">
        <span class="footer-brand">${brand}</span>
        <span class="footer-copy">© ${year} ${brand}. All rights reserved.</span>
        <nav class="footer-links" aria-label="Footer navigation">
          ${linkItems}
        </nav>
      </div>
    </footer>`;
}

function renderTestimonial(comp) {
  const quote    = esc(comp.properties?.content || comp.properties?.quote || 'This product exceeded every expectation.');
  const author   = comp.properties?.author   || 'Customer';
  const role     = esc(comp.properties?.role     || comp.properties?.title || '');
  const location = esc(comp.properties?.location || '');
  const stars    = comp.properties?.stars    != null ? comp.properties.stars : 5;
  const initials = author.split(' ').map(n => n[0]).join('').toUpperCase().slice(0, 2);
  const roleLocation = [role, location].filter(Boolean).join(' · ');
  return `
    <div class="testimonial-card" id="${esc(comp.id || 'testimonial')}">
      <div class="testimonial-stars">${renderStars(stars)}</div>
      <p class="testimonial-quote">"${quote}"</p>
      <div class="testimonial-author">
        <div class="testimonial-avatar" aria-hidden="true">${esc(initials)}</div>
        <div>
          <p class="testimonial-name">${esc(author)}</p>
          ${roleLocation ? `<p class="testimonial-role">${roleLocation}</p>` : ''}
        </div>
      </div>
    </div>`;
}

function renderPricingCard(comp) {
  const plan = esc(comp.properties?.title || 'Starter');
  const price = esc(comp.properties?.price || '$0');
  const features = Array.isArray(comp.properties?.features)
    ? comp.properties.features
    : ['Core features', 'Basic support', 'Up to 5 projects'];
  const highlighted = comp.properties?.highlighted;
  return `
    <div class="pricing-card ${highlighted ? 'highlighted' : ''}" id="${esc(comp.id || 'pricing')}">
      ${highlighted ? '<span class="pricing-badge">Most Popular</span>' : ''}
      <p class="pricing-plan">${plan}</p>
      <div style="margin-bottom:1.5rem">
        <span class="pricing-price">${price}</span>
        <span class="pricing-period">/month</span>
      </div>
      <ul class="pricing-features">
        ${features.slice(0, 5).map(f => `<li>${esc(f)}</li>`).join('\n        ')}
      </ul>
      <a href="#" class="btn ${highlighted ? 'btn-primary' : 'btn-outline'} w-full" style="justify-content:center">Get Started</a>
    </div>`;
}

function renderBanner(comp) {
  const title = esc(comp.properties?.title || '🎉 Special Offer');
  const subtitle = esc(comp.properties?.subtitle || "Limited time deal \u2014 don't miss out!");
  return `
    <div class="banner" id="${esc(comp.id || 'banner')}">
      <div class="banner-text">
        <h4>${title}</h4>
        <p>${subtitle}</p>
      </div>
      <a href="#" class="btn btn-primary btn-sm">Claim Now</a>
    </div>`;
}

function renderList(comp) {
  const title = esc(comp.properties?.title || 'Links');
  const items = Array.isArray(comp.properties?.items)
    ? comp.properties.items
    : ['Item One', 'Item Two', 'Item Three'];
  return `
    <div class="list-card" id="${esc(comp.id || 'list')}">
      <div class="list-card-header">${title}</div>
      ${items.slice(0, 6).map(item => `
      <div class="list-item">
        <span>${esc(typeof item === 'string' ? item : item.label || '')}</span>
        <span class="list-arrow">›</span>
      </div>`).join('')}
    </div>`;
}

function renderStatsBar(comp) {
  const stats = Array.isArray(comp.properties?.stats)
    ? comp.properties.stats
    : [{ label: 'Revenue', value: '$248K', change: '+14%' }, { label: 'Users', value: '12.8K', change: '+8.7%' }];
  return `
    <div class="stats-bar" id="${esc(comp.id || 'stats')}">
      ${stats.map(s => {
        const isNeg = String(s.change || '').includes('-');
        return `
      <div class="stats-bar-item">
        <p class="stats-label">${esc(s.label || '')}</p>
        <p class="stats-value">${esc(s.value || '')}</p>
        ${s.change ? `<p class="stats-change" style="color:${isNeg ? '#f87171' : '#34d399'}">${esc(s.change)}</p>` : ''}
      </div>`;
      }).join('')}
    </div>`;
}

function renderProductCard(comp) {
  const name     = esc(comp.properties?.title    || comp.properties?.name  || 'Product');
  const price    = esc(comp.properties?.price    || '$0.00');
  const badge    = comp.properties?.badge;
  const rating   = comp.properties?.rating;
  const category = comp.properties?.category;
  const ratingCount = comp.properties?.ratingCount || comp.properties?.reviews;

  const rawName  = comp.properties?.title || comp.properties?.name || 'Product';
  const imgUrl   = getPollinationsImageUrl(comp.properties?.imagePrompt || rawName, 400, 240, getStableSeed(rawName));
  const imgHtml  = `<img src="${esc(imgUrl)}" alt="${name}" style="width:100%;height:100%;object-fit:cover;" />`;

  return `
    <div class="product-card" id="${esc(comp.id || 'product')}">
      <div class="product-image" style="padding:0;overflow:hidden;">
        ${badge ? `<span class="product-badge">${esc(badge)}</span>` : ''}
        ${imgHtml}
      </div>
      <div class="product-info">
        ${category ? `<p class="product-category">${esc(category)}</p>` : ''}
        <p class="product-name">${name}</p>
        ${rating != null ? `<div class="product-rating">${renderStars(rating)}${ratingCount ? `<span class="product-rating-count">(${esc(String(ratingCount))})</span>` : ''}</div>` : ''}
        <div class="product-actions">
          <span class="product-price">${price}</span>
          <a href="#" class="btn btn-primary btn-sm">Add to Cart</a>
        </div>
      </div>
    </div>`;
}

/** Derive a gradient color pair from a label/keyword for product image slots */
function _productGradient(label) {
  const l = (label || '').toLowerCase();
  if (/gold|golden|luxury/.test(l))    return ['#b8860b', '#d4af37'];
  if (/diamond|crystal|gem/.test(l))   return ['#a8d8f0', '#6cb4e4'];
  if (/silver|steel|metal/.test(l))    return ['#708090', '#a9b9c0'];
  if (/rose|pink|blush/.test(l))       return ['#c4627a', '#e8a0b0'];
  if (/ruby|red|garnet/.test(l))       return ['#9b1b30', '#d9534f'];
  if (/emerald|green|jade/.test(l))    return ['#046307', '#3cb371'];
  if (/sapphire|blue|aqua/.test(l))    return ['#0f3460', '#16213e'];
  if (/pearl|white|ivory/.test(l))     return ['#f8f8ff', '#d3d3d3'];
  if (/new|sale|hot/.test(l))          return ['#7c3aed', '#a855f7'];
  return ['var(--color-primary)', 'var(--color-secondary)'];
}

/** Pick an emoji icon based on product category/badge keyword */
function _productIcon(label) {
  const l = (label || '').toLowerCase();
  if (/ring/.test(l))       return '💍';
  if (/necklace|chain/.test(l)) return '📿';
  if (/bracelet|bangle/.test(l)) return '📿';
  if (/earring/.test(l))    return '✨';
  if (/watch/.test(l))      return '⌚';
  if (/diamond/.test(l))    return '💎';
  if (/gold/.test(l))       return '🏅';
  if (/silver/.test(l))     return '🥈';
  if (/bag|purse/.test(l))  return '👜';
  if (/shoe|boot/.test(l))  return '👠';
  if (/shirt|top|cloth/.test(l)) return '👗';
  if (/phone|tech/.test(l)) return '📱';
  if (/book/.test(l))       return '📚';
  return '🛍️';
}

function renderSidebar(comp, schema) {
  const items = comp.properties?.menuItems || [
    { label: 'Dashboard' }, { label: 'Analytics' }, { label: 'Settings' }
  ];
  const brand = esc(comp.properties?.brand || 'App');
  const initial = brand.charAt(0).toUpperCase();
  const pages = schema?.pages || [];
  return `
    <aside class="sidebar" id="${esc(comp.id || 'sidebar')}" aria-label="Sidebar navigation">
      <div class="sidebar-logo">
        <div class="sidebar-logo-icon" aria-hidden="true">${initial}</div>
        <span>${brand}</span>
      </div>
      <nav aria-label="Sidebar">
        ${items.map((item, i) => {
          const label = typeof item === 'string' ? item : item.label || '';
          const href = getPageHref(typeof item === 'string' ? item : item.path || item.label || '', pages);
          return `<a href="${esc(href)}" class="sidebar-item${i === 0 ? ' active' : ''}">${esc(label)}</a>`;
        }).join('\n        ')}
      </nav>
    </aside>`;
}

function renderCard(comp) {
  const title   = esc(comp.properties?.title   || 'Feature');
  const content = esc(comp.properties?.content || comp.properties?.description || '');
  const icon    = comp.properties?.icon || 'fa-cubes';
  const iconHtml = icon
    ? `<div style="width:40px;height:40px;background:rgba(124,58,237,0.12);border-radius:10px;margin-bottom:1rem;display:flex;align-items:center;justify-content:center;"><i class="fa-solid ${esc(icon)}" style="color:var(--color-primary);font-size:1.1rem;"></i></div>`
    : `<div style="width:40px;height:40px;background:var(--color-primary);opacity:0.12;border-radius:10px;margin-bottom:1rem;"></div>`;

  let innerHtml = '';

  // 1. Check for product list or items list (grid)
  const productList = comp.properties?.products || comp.properties?.items;
  if (productList && Array.isArray(productList)) {
    innerHtml = `
      <div style="display:grid;grid-template-columns:repeat(auto-fill, minmax(200px, 1fr));gap:var(--space-md);margin-top:var(--space-md);">
        ${productList.map(p => {
          const nameVal = p.name || p.title || 'Product';
          const priceVal = p.price || '';
          const imgUrl = getPollinationsImageUrl(p.imagePrompt || nameVal, 300, 200, getStableSeed(nameVal));
          const imgHtml = `<img src="${esc(imgUrl)}" alt="${esc(nameVal)}" style="width:100%;height:100%;object-fit:cover;" />`;
          return `
          <div style="background:rgba(255,255,255,0.02);border:1px solid var(--color-border);border-radius:var(--radius-md);padding:var(--space-md);display:flex;flex-direction:column;justify-content:between;">
            <div style="height:120px;border-radius:var(--radius-sm);overflow:hidden;margin-bottom:var(--space-sm);border:1px solid var(--color-border);">
              ${imgHtml}
            </div>
            <p style="font-size:0.875rem;font-weight:600;margin-bottom:4px;">${esc(nameVal)}</p>
            <div style="display:flex;justify-content:space-between;align-items:center;margin-top:auto;">
              <span style="font-size:0.875rem;font-weight:800;color:var(--color-primary);">${esc(priceVal)}</span>
              <a href="#" class="btn btn-primary btn-sm" style="padding:4px 8px;font-size:0.75rem;">Add</a>
            </div>
          </div>`;
        }).join('')}
      </div>`;
  }
  // 2. Check for details (profile / name value list)
  else if (comp.properties?.details && Array.isArray(comp.properties.details)) {
    innerHtml = `
      <div style="display:flex;flex-direction:column;gap:var(--space-sm);margin-top:var(--space-md);">
        ${comp.properties.details.map(d => `
        <div style="display:flex;justify-content:space-between;border-bottom:1px solid var(--color-border);padding-bottom:var(--space-xs);font-size:0.875rem;">
          <span class="text-muted">${esc(d.label || '')}</span>
          <span style="font-weight:500;">${esc(d.value || '')}</span>
        </div>`).join('')}
      </div>`;
  }
  // 3. Check for specific product detail view card layout
  else if (comp.properties?.price || comp.properties?.image || comp.properties?.imagePrompt) {
    const price = esc(comp.properties.price || '');
    const desc = esc(comp.properties.description || comp.properties.content || content);
    const titleVal = esc(comp.properties.title || '');
    const rawTitle = comp.properties.title || '';
    const imgUrl = getPollinationsImageUrl(comp.properties.imagePrompt || rawTitle, 400, 400, getStableSeed(rawTitle));
    const imgHtml = `<img src="${esc(imgUrl)}" alt="${titleVal}" style="width:100%;height:100%;object-fit:cover;" />`;
    
    innerHtml = `
      <div style="display:flex;gap:var(--space-xl);margin-top:var(--space-md);flex-wrap:wrap;">
        <div style="width:180px;height:180px;border-radius:var(--radius-lg);overflow:hidden;flex-shrink:0;border:1px solid var(--color-border);">
          ${imgHtml}
        </div>
        <div style="flex:1;min-width:240px;display:flex;flex-direction:column;justify-content:center;">
          <h2 style="font-size:1.5rem;font-weight:700;margin-bottom:0.5rem;">${titleVal}</h2>
          <p class="text-muted" style="margin-bottom:var(--space-md);">${desc}</p>
          ${price ? `<p style="font-size:1.75rem;font-weight:900;color:var(--color-primary);margin-bottom:var(--space-md);">${price}</p>` : ''}
        </div>
      </div>`;
  }
  // 4. Default feature card style
  else {
    const imgPrompt = comp.properties?.imagePrompt;
    const cardImgHtml = imgPrompt 
      ? `<div style="width:100%;height:130px;border-radius:var(--radius-md);overflow:hidden;margin-bottom:1rem;border:1px solid var(--color-border);">
          <img src="${esc(getPollinationsImageUrl(imgPrompt, 400, 250, getStableSeed(imgPrompt)))}" alt="${title}" style="width:100%;height:100%;object-fit:cover;" />
        </div>`
      : '';
    innerHtml = `
      ${cardImgHtml}
      ${iconHtml}
      <h3 style="font-size:1rem;font-weight:700;margin-bottom:0.5rem;">${title}</h3>
      ${content ? `<p class="text-muted" style="font-size:0.875rem;line-height:1.6;">${content}</p>` : ''}
      <a href="#" class="btn btn-ghost btn-sm" style="margin-top:1rem;padding-left:0;">Learn More →</a>`;
  }

  return `
    <div class="card" id="${esc(comp.id || 'card')}">
      ${innerHtml}
    </div>`;
}

// ─── Collection Card ───────────────────────────────────────────────────────

function renderCollectionCard(comp) {
  const name  = esc(comp.properties?.name  || comp.properties?.title || 'Collection');
  const desc  = esc(comp.properties?.description || comp.properties?.subtitle || '');
  const count = comp.properties?.count || comp.properties?.items || null;
  const cta   = esc(comp.properties?.cta   || 'Explore Collection');

  // Derive gradient from collection name/theme
  const gradients = _productGradient(name);
  const bg = `linear-gradient(135deg, ${gradients[0]}, ${gradients[1]})`;
  const icon = _productIcon(name);

  return `
    <div class="collection-card" id="${esc(comp.id || 'collection')}">
      <div class="collection-card-bg" style="background:${bg};" aria-hidden="true">
        <div style="display:flex;align-items:center;justify-content:center;height:100%;font-size:3.5rem;opacity:0.25;">${icon}</div>
      </div>
      <div class="collection-card-content">
        <p class="collection-card-name">${name}</p>
        ${desc ? `<p class="collection-card-desc">${desc}</p>` : ''}
        <div style="display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:8px;">
          ${count ? `<span class="collection-card-meta">${esc(String(count))} pieces</span>` : ''}
          <a href="#" class="btn btn-outline btn-sm" style="border-color:rgba(255,255,255,0.5);color:#fff;">${cta} →</a>
        </div>
      </div>
    </div>`;
}

// ─── Image Component ───────────────────────────────────────────────────────

function renderImage(comp) {
  const prompt = comp.properties?.imagePrompt || comp.properties?.title || comp.properties?.content || 'illustration';
  const aspectRatio = comp.properties?.aspectRatio || '16:9';

  let paddingBottom = '56.25%'; // default 16:9
  if (aspectRatio === '1:1') paddingBottom = '100%';
  else if (aspectRatio === '4:3') paddingBottom = '75%';
  else if (aspectRatio === '21:9') paddingBottom = '42.85%';
  else if (aspectRatio === '3:2') paddingBottom = '66.67%';

  const rawPrompt = comp.properties?.imagePrompt || comp.properties?.title || comp.properties?.content || 'mockup';
  const imgUrl = getPollinationsImageUrl(rawPrompt, 800, 450, getStableSeed(rawPrompt));

  return `
    <div id="${esc(comp.id || 'image')}" class="image-card" style="width:100%;padding-bottom:${paddingBottom};position:relative;border-radius:var(--radius-lg);overflow:hidden;border:1px solid var(--color-border);background-color:rgba(255,255,255,0.02);">
      <img src="${esc(imgUrl)}" alt="${esc(prompt)}" style="position:absolute;top:0;left:0;width:100%;height:100%;object-fit:cover;object-position:center;" />
    </div>`;
}

// ─── Main component dispatcher ─────────────────────────────────────────────

/**
 * @param {object} comp   - Component object from the schema
 * @param {object} [schema] - Full design schema (used by footer for navigation links)
 */
function renderComponent(comp, schema) {
  switch (comp.type) {
    case 'navbar':           return renderNavbar(comp, schema);
    case 'hero':             return renderHero(comp);
    case 'metric-card':      return renderMetricCard(comp);
    case 'chart':            return renderChart(comp);
    case 'table':
    case 'data-table':       return renderDataTable(comp);
    case 'form':             return renderForm(comp);
    case 'button':           return renderButton(comp);
    case 'footer':           return renderFooter(comp, schema);
    case 'testimonial':      return renderTestimonial(comp);
    case 'pricing-card':     return renderPricingCard(comp);
    case 'banner':           return renderBanner(comp);
    case 'list':             return renderList(comp);
    case 'stats-bar':        return renderStatsBar(comp);
    case 'product-card':     return renderProductCard(comp);
    case 'collection-card':  return renderCollectionCard(comp);
    case 'sidebar':          return renderSidebar(comp, schema);
    case 'card':             return renderCard(comp);
    case 'image':            return renderImage(comp);
    default:
      return `
    <div class="card" id="${esc(comp.id || comp.type)}" style="opacity:0.7">
      <p class="metric-label">${esc(comp.type)}</p>
      <h3>${esc(comp.label || comp.properties?.title || comp.type)}</h3>
    </div>`;
  }
}

// ─── Page HTML builder ─────────────────────────────────────────────────────

function buildPageHtml(page, schema, projectName, isIndex = false) {
  const colors = schema?.tokens?.colors || {};
  const typo = schema?.tokens?.typography || {};
  const headingFont = typo.headingFont || 'Outfit';
  const bodyFont = typo.bodyFont || 'Inter';
  const bgColor = page.layout?.background || colors.background || '#0f172a';
  const pageName = esc(page.name || 'Page');
  const title = `${esc(projectName)} — ${pageName}`;
  const cssPath = isIndex ? 'styles.css' : '../styles.css';

  const hasSidebar = page.components?.some(c => c.type === 'sidebar');
  const sidebarComp = page.components?.find(c => c.type === 'sidebar');
  const otherComps = page.components?.filter(c => c.type !== 'sidebar') || [];

  // Detect special full-width components
  const fullWidthTypes = new Set(['navbar', 'footer', 'banner', 'hero', 'stats-bar']);

  // Build body content
  let bodyContent = '';

  if (hasSidebar) {
    // Layout with sidebar
    const sidebarHtml = renderComponent(sidebarComp, schema);
    const contentComps = otherComps.filter(c => c.type !== 'navbar' && c.type !== 'footer');
    const navbarComp = otherComps.find(c => c.type === 'navbar');
    const footerComp = otherComps.find(c => c.type === 'footer');

    if (navbarComp) bodyContent += renderComponent(navbarComp, schema);

    bodyContent += `\n  <div class="layout-with-sidebar">`;
    bodyContent += sidebarHtml;
    bodyContent += `\n    <main class="sidebar-content">`;

    // Grid layout for content components
    const gridComps = contentComps.filter(c => !fullWidthTypes.has(c.type));
    if (gridComps.length > 0) {
      bodyContent += `\n      <div class="grid-12" style="margin-bottom:1.5rem;">`;
      gridComps.forEach(comp => {
        const pos = comp?.responsive?.desktop?.position || comp?.position || {};
        const span = Math.max(1, Math.min(12, pos.w ?? 12));
        bodyContent += `\n        <div class="col-span-${span}">${renderComponent(comp, schema)}\n        </div>`;
      });
      bodyContent += `\n      </div>`;
    }

    bodyContent += `\n    </main>\n  </div>`;
    if (footerComp) bodyContent += renderComponent(footerComp, schema);
  } else {
    // Re-process with grid grouping
    let i = 0;
    const comps = otherComps;
    while (i < comps.length) {
      const comp = comps[i];
      if (fullWidthTypes.has(comp.type)) {
        bodyContent += renderComponent(comp, schema);
        i++;
      } else {
        // Gather consecutive non-fullwidth components into a shared grid row
        bodyContent += `\n  <div class="page-wrapper"><div class="grid-12">`;
        while (i < comps.length && !fullWidthTypes.has(comps[i].type)) {
          const c = comps[i];
          const pos = c?.responsive?.desktop?.position || c?.position || {};
          const span = Math.max(1, Math.min(12, pos.w ?? 6));
          bodyContent += `\n    <div class="col-span-${span}">${renderComponent(c, schema)}\n    </div>`;
          i++;
        }
        bodyContent += `\n  </div></div>`;
      }
    }
  }

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="${esc(projectName)} — ${pageName}">
  <title>${title}</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="stylesheet" href="${cssPath}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" crossorigin="anonymous">
  <style>
    /* Page-specific overrides */
    body { background-color: ${bgColor}; }
  </style>
</head>
<body>
${bodyContent}
</body>
</html>`;
}

// ─── Main Export Function ───────────────────────────────────────────────────

/**
 * Generates an array of { filename, content } file objects from the schema.
 * @param {object} schema
 * @param {object} options - { projectName }
 * @returns {Promise<{ type: 'files', files: Array<{filename, content, mimeType}> }>}
 */
export async function generateHtmlCssExport(schema, options = {}) {
  const projectName =
    options.projectName ||
    schema?.meta?.projectName ||
    'design-export';

  const pages = schema?.pages || [];
  const cssContent = generateCSS(schema);
  const files = [];

  // styles.css (shared)
  files.push({ filename: 'styles.css', content: cssContent, mimeType: 'text/css' });

  // index.html → first page
  if (pages.length > 0) {
    files.push({
      filename: 'index.html',
      content: buildPageHtml(pages[0], schema, projectName, true),
      mimeType: 'text/html',
    });
  }

  // Additional pages
  pages.slice(1).forEach(page => {
    const pageName = slugify(page.name || page.id || `page-${pages.indexOf(page)}`);
    files.push({
      filename: `${pageName}.html`,
      content: buildPageHtml(page, schema, projectName, false),
      mimeType: 'text/html',
    });
  });

  // README
  files.push({
    filename: 'README.md',
    content: generateReadme(schema, projectName, files),
    mimeType: 'text/markdown',
  });

  return { type: 'files', files };
}

// ─── README Generator ──────────────────────────────────────────────────────

function generateReadme(schema, projectName, files) {
  const pages = schema?.pages || [];
  const colors = schema?.tokens?.colors || {};
  const typo = schema?.tokens?.typography || {};

  return `# ${projectName}

> Generated by [AI UI/UX Design Platform](https://github.com) on ${new Date().toLocaleDateString()}

## Project Info

| Property | Value |
|---|---|
| Project Type | ${schema?.meta?.projectType || 'Web Application'} |
| Theme | ${schema?.meta?.theme || 'dark'} |
| Pages | ${pages.length} |
| Components | ${pages.reduce((s, p) => s + (p.components?.length || 0), 0)} |

## Files

${files.map(f => `- \`${f.filename}\` — ${f.mimeType}`).join('\n')}

## Design Tokens

### Colors
${Object.entries(colors).map(([k, v]) => `- **${k}**: \`${v}\``).join('\n')}

### Typography
- **Heading Font**: ${typo.headingFont || 'Outfit'}
- **Body Font**: ${typo.bodyFont || 'Inter'}

## Pages

${pages.map((p, i) => `### ${i + 1}. ${p.name || p.id}
- **Path**: \`${p.path || '/'}\`
- **Components**: ${(p.components || []).map(c => c.type).join(', ')}
`).join('\n')}

## Usage

1. Open \`index.html\` in any modern browser
2. No build step required — pure HTML & CSS
3. Google Fonts and FontAwesome are loaded via CDN
4. Edit \`styles.css\` to customize the design tokens

## Browser Support

- Chrome 90+, Firefox 88+, Safari 14+, Edge 90+

---

*This project was generated by the AI UI/UX Design Platform. Edit freely — the code is yours.*
`;
}
